theme: jekyll-theme-architect

title: Dave Boster
email: david@boster.us
description: How Fascinating! ＼(๏◡๏)／
twitter_username: davidboster
github_username: daveboster

collections:
  thoughts:
    output: true
    permalink: /thoughts/:path/

paginate: 6
paginate_path: "/blog/page:num/"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - LICENSE
  - README.md
  - docs/

plugins:
  - jekyll-paginate
