name: Boster.dev CI/CD

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/bosterdev-deploy.yml'
      - 'src/boster.dev/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - '.github/workflows/bosterdev-deploy.yml'
      - 'src/boster.dev/**'

jobs:
  build_and_deploy_job:
    defaults:
      run:
        # jobs.<job_id>.defaults.run
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrun
        working-directory: ./src/boster.dev/

    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Install Jekyll
        run: gem install bundler github-pages jekyll-paginate

      - name: Jekyll build
        run: jekyll build

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          skip_app_build: true
          app_location: "${{ github.workspace }}/src/boster.dev/_site" # App source code path

  close_pull_request_job:
    defaults:
      run:
        # jobs.<job_id>.defaults.run
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrun
        working-directory: ./src/boster.dev/

    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
